services:
  - type: web
    name: abujal-service
    env: dotnet
    rootDir: AbujalWebsite
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/AbujaWebsite.dll --urls=http://0.0.0.0:$PORT"
    plan: free